name:                MCFISP
version:             0.1.0.0
github:              "githubuser/MCFISP"
license:             BSD3
author:              "Gabriel Siqueira"
maintainer:          "gabriel.siqueira@ic.unicamp.br"
copyright:           "2023 Gabriel Siqueira"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MCFISP#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- containers
- hashable
- hedgehog
- MonadRandom
- random
- random-shuffle
- vector
- parallel-io
- deepseq
- time
- optparse-applicative
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  MCFISP-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -main-is Main
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MCFISP

  DB-exe:
    main:                DB.hs
    source-dirs:         app
    ghc-options:
    - -main-is DB
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MCFISP

tests:
  MCFISP-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MCFISP
